# Generated by Django 5.0.7 on 2024-08-06 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 6, 10, 38, 38, 167245), editable=False),
        ),
    ]
