# Generated by Django 5.0.7 on 2024-08-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
