# Generated by Django 5.0.7 on 2024-08-06 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usersdata_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersdata',
            name='is_online',
        ),
    ]
