# Generated by Django 5.0.7 on 2024-09-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usersdata_consultants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='id',
            field=models.CharField(default='2a5ef1533c4bb06835292ba2', max_length=24, primary_key=True, serialize=False),
        ),
    ]
