# Generated by Django 5.0.7 on 2024-08-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_usersdata_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
