# Generated by Django 5.0.7 on 2024-08-12 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_usersdata_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='consultants',
            field=models.ManyToManyField(blank=True, null=True, related_name='consulted_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
